title: spkerkela.com
email: simo-pekka.kerkela@spkerkela.com
description: >-
  My personal site where I intend to post my thoughts on things important to me,
  such as  software, music and wellbeing.
baseurl: ''
url: 'https://spkerkela.com'
twitter_username: spkerkela
github_username: spkerkela
micro_blog_username: spkerkela
gitea_username: spkerkela
githost: 'git.spkerkela.com'
projects:
  - average_color: null
    url: 'https://averagecolor.com'
    name: Get Average Color of Image
  - lorem_gen: null
    url: 'https://github.com/spkerkela/lorem'
    name: CLI Lorem Ipsum Generator
  - gem_game: null
    url: 'https://spkerkela.github.io/gemhunter/'
    name: Simple Web Game
  - sodotory: null
    url: 'https://sodotory.com/'
    name: Band Website
mastodon:
  - technology: null
    username: spk
    instance: mastodon.technology
header_pages:
  - about.md
  - projects.md
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
